-- Foundation: extensions, shared trigger functions and reference data.
--
-- Conventions (apply to every migration):
--   * Primary keys are UUID v7 generated by the application.
--   * Timestamps are TIMESTAMPTZ (UTC). Every mutable table has created_at/updated_at.
--   * Money is NUMERIC(19,4) + CHAR(3) currency referencing currencies(code).
--   * Statuses are TEXT with CHECK constraints (easy to evolve, mapped to Rust enums).
--   * JSONB only for genuinely schemaless data (audit metadata, job payloads, raw webhooks).
--   * Never edit a migration after it has been deployed. Add a new one.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE currencies (
    code        CHAR(3)  PRIMARY KEY CHECK (code ~ '^[A-Z]{3}$'),
    name        TEXT     NOT NULL,
    minor_units SMALLINT NOT NULL CHECK (minor_units BETWEEN 0 AND 4),
    is_active   BOOLEAN  NOT NULL DEFAULT TRUE
);

INSERT INTO currencies (code, name, minor_units) VALUES
    ('LKR', 'Sri Lankan Rupee', 2),
    ('USD', 'US Dollar', 2),
    ('INR', 'Indian Rupee', 2),
    ('CNY', 'Chinese Yuan', 2),
    ('AED', 'UAE Dirham', 2),
    ('EUR', 'Euro', 2);

CREATE TABLE countries (
    code      CHAR(2) PRIMARY KEY CHECK (code ~ '^[A-Z]{2}$'),
    name      TEXT    NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- TODO: load the full ISO 3166-1 list in a dedicated reference-data migration.
INSERT INTO countries (code, name) VALUES
    ('LK', 'Sri Lanka'),
    ('IN', 'India'),
    ('CN', 'China'),
    ('AE', 'United Arab Emirates'),
    ('US', 'United States'),
    ('GB', 'United Kingdom'),
    ('DE', 'Germany'),
    ('SG', 'Singapore'),
    ('MY', 'Malaysia'),
    ('TH', 'Thailand'),
    ('JP', 'Japan');
